### ISSUE TITLE
Error: Found multiple packages matching name: jam:easy-schema

### ISSUE THREAD

**Issue by HemalR** [jamauro/easy-schema#3]
Hi,

I'm testing this package out as a replacement for Collection2 but am running into this error when trying to install it.

```
meteor add jam:easy-schema

Error: Found multiple packages matching name: jam:easy-schema
```

Am I doing something very basic wrong?

Thanks in advance!

**Comment by jamauro** [comment]
Hey, thanks for letting me know. There is a bug with Meteor's package repository, Atmosphere, so to get around it, you'll need to clear the packages cache on your machine. 

Here's how to do it on a Mac:
```
1. sudo rm /usr/local/bin/meteor
2. rm -rf ~/.meteor
3. curl https://install.meteor.com/ | sh
```

**Comment by HemalR** [comment]
Hmm, weirdly I don't have any meteor files in my bin folder. I have Meteor installed (obv) and everything runs fine, odd that I don't have a bin file 😕 

Maybe I have the cache in a different location? Or is this something else?

**Comment by jamauro** [comment]
Did you try running those commands above in your terminal? If you’re on a Mac, that should work and you should be able to add the package.

**Comment by HemalR** [comment]
I did, but they didn't work as the bin file wasn't there. However, since you let me know it's a caching issue, I did remove and reinstall meteor which did, indeed, fix the issue. 👍

I'll close this accordingly.

A follow up question (please let me know if you prefer this to be asked/discussed in the forums instead):

I'm trying to migrate over from SimplSchema to this. A question on typescript - I can see the .d.ts file you have published: https://github.com/jamauro/easy-schema/blob/main/easy-schema.d.ts

However, for some reason it isn't getting picked up in my project:

`Property 'attachSchema' does not exist on type CollectionName...`

 I do have zodern:types set up, configured and running successfully.  Any other ideas? Not sure if related (probably!) but importing is causing an error as well:

```
import { AnyOf, Optional } from "meteor/jam:easy-schema"; //  File ..../.meteor/local/types/packages.d.ts' is not a module.
```

**Comment by jamauro** [comment]
Thanks. Glad you were able to add the package. 

Would you mind opening a separate  GitHub issue for the typescript issue you're seeing? Also if you can list the other packages you have installed. I'll try to repro it. Thanks!

**Comment by HemalR** [comment]
Sure. Done here: https://github.com/jamauro/easy-schema/issues/4
