### ISSUE TITLE
Recommended way to use with Typescript

### ISSUE THREAD

**Issue by HemalR** [jamauro/easy-schema#4]
I'm trying to migrate over from SimplSchema to this. A question on typescript - I can see the .d.ts file you have published: https://github.com/jamauro/easy-schema/blob/main/easy-schema.d.ts

However, for some reason it isn't getting picked up in my project:

`Property 'attachSchema' does not exist on type CollectionName...`

I do have zodern:types set up, configured and running successfully. Any other ideas? Not sure if related (probably!) but importing is causing an error as well:

```
import { AnyOf, Optional } from "meteor/jam:easy-schema"; //  File ..../.meteor/local/types/packages.d.ts' is not a module.
```

<img width="1101" alt="image" src="https://github.com/jamauro/easy-schema/assets/15634303/04a9aa20-9194-4328-b3f0-184335c8eedf">

Reproduction here: https://github.com/HemalR/simple-todos-react

Thanks in advance for any guidance.

**Comment by jamauro** [comment]
Hmm interesting. I'll look into this further. In the meantime, can you try updating your tsconfig by replacing the `exclude` with this:

```
"exclude": [
    "./.meteor/**",
    "!./.meteor/local/types",
    "./packages/**"
  ]
  ```

**Comment by HemalR** [comment]
Tried that out. No changes though.

**Comment by jamauro** [comment]
Thanks. Can you try removing the package and then adding it with the specific version:

`meteor add jam:easy-schema@1.3.0-alpha300.19`

Long story short, this should install the latest version of the package. Atmosphere doesn’t recognize it as being the latest version because of the alpha tag which is only there for 3.0 compatibility reasons. It’ll be removed once there’s a 3.0 RC.

**Comment by jamauro** [comment]
@HemalR I pulled your sample project. Thanks for putting that together. When I added `meteor add jam:easy-schema@1.3.0-alpha300.19` everything appears to work correctly.

**Comment by HemalR** [comment]
I'm still getting that same `not a module` warning. All I've tried doing is remove the package and `meteor add jam:easy-schema@1.3.0-alpha300.19`. Was there any additional config I've missed?

(If you've tested it against my example repo I can check it there as well if you push it to that).

**Comment by jamauro** [comment]
Ok I made a PR to update the package version in your sample repo. 

If you’re still seeing the issue, try running `meteor lint` in your cli and restarting your code editor. 

Assuming it works in your sample repo for you as it does for me, then if you’re seeing the issue in a different project, my best guess is that you’ll need to use the above `exclude` in your tsconfig: https://github.com/jamauro/easy-schema/issues/4#issuecomment-1992545613

**Comment by HemalR** [comment]
`meteor lint` fixed it after all else failed!

![image](https://github.com/jamauro/easy-schema/assets/15634303/0c87f142-2e65-47bc-a0f7-bbebd2152cac)

I wasn't even aware of that command, good to know.

Thank you very much!
