### ISSUE TITLE
AnyOf in version 1.5.0

### ISSUE THREAD

**Issue by mcorbelli** [jamauro/easy-schema#6]
Upgrading to version 1.5.0 causes issues with my application. Specifically, I’ve identified problems with the use of AnyOf. It was working fine before, but I haven’t noticed any breaking changes. I’m getting a validation error.

Meteor 3.0.3

`
Schema.getVendorParticipationsSchema = {
  filter: Optional(
    AnyOf(
      {
        type: String,
        allow: Object.values(AllEventFilters),
      },
      null,
      undefined,
    ),
  ),
};
`

**Comment by jamauro** [comment]
`allow` was renamed to `enums` in `v1.5.0`.

**Comment by mcorbelli** [comment]
Thanks
